version: '2'
exclude_patterns:
  - 'bin/'
  - 'config/'
  - 'db/'
  - 'app/channels'
  - 'app/jobs'
  - 'app/mailers'
  - 'app/controllers/user_controller.rb'
  - 'node_modules/'
  - 'spec/'
  - 'vendor/'
