inherit_from: .rubocop_todo.yml

inherit_gem:
  niftany: niftany_rubocop.yml

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'


# This does not play well with the doorkeeper-openid_connect gem
Style/SymbolProc:
  Exclude:
    - 'config/initializers/doorkeeper_openid_connect.rb' 
