version: '3.5'
services:
  test:
    tty: true
    stdin_open: true
    environment:
      OIDC_SIGNING_KEY: ${OIDC_SIGNING_KEY:-Zm9vCg==}
      OIDC_ISSUER: ${OIDC_ISSUER:-http://localhost:3000}
      RAILS_SERVE_STATIC_FILES: "true"
      CIRCLE_SHA1: ${CIRCLE_SHA1}
      CC_TEST_REPORTER_ID: ${CC_TEST_REPORTER_ID}
      CIRCLE_BRANCH: ${CIRCLE_BRANCH}
      GIT_COMMITED_AT: ${GIT_COMMITED_AT}
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
      POSTGRES_USER: psuauthproxy
      POSTGRES_HOST: db
      POSTGRES_DB: psuauthproxy
      POSTGRES_PASSWORD: psuauthproxy
    image: harbor.dsrd.libraries.psu.edu/library/psu-authproxy:$TAG
