version: '3.5'
services:
  db:
    environment:
      POSTGRES_PASSWORD: psuauthproxy
      POSTGRES_USER: psuauthproxy
      POSTGRES_DB: psuauthproxy
    image: postgres:10
    ports:
    - "5433:5432"
    volumes:
    - db-data:/var/lib/postgresql/data
  web:
    tty: true
    stdin_open: true
    environment:
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
      POSTGRES_USER: psuauthproxy
      POSTGRES_HOST: db
      POSTGRES_DB: psuauthproxy
      POSTGRES_PASSWORD: psuauthproxy
    build: 
      context: .
      target: base
    command: >
      sh -c "echo starting database migrations &&
            yarn &&
            rm -f tmp/pids/server.pid
            bundle exec rails db:migrate &&
            echo starting rails &&
            bundle exec rails s -b 0.0.0.0"
    volumes:
      - /app/vendor/bundle
      - /app/node_modules
      - type: bind
        source: .
        target: /app/
        consistency: cached
    ports:
    - "3001:3000"
    depends_on:
    - db

volumes:
  db-data:
