version: '3.2'
services:
  adminer:
    image: adminer
    restart: always
    ports:
    - "8080:8080"
  db:
    environment:
      POSTGRES_PASSWORD: psuauthproxy
      POSTGRES_USER: psuauthproxy
      POSTGRES_DB: psuauthproxy
    image: postgres:10
    ports:
    - "5433:5432"
    volumes:
    - db-data:/var/lib/postgresql/data
  web:
    environment:
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
      POSTGRES_USER: psuauthproxy
      POSTGRES_HOST: db
      POSTGRES_DB: psuauthproxy
      POSTGRES_PASSWORD: psuauthproxy
    build: .
    command: >
      sh -c "echo starting database migrations &&
            yarn &&
            bundle exec rails db:migrate &&
            echo starting rails &&
            bundle exec rails s -b 0.0.0.0"
    volumes:
      - type: bind
        source: .
        target: /app/
        consistency: cached
    ports:
    - "3001:3000"
    depends_on:
    - db

volumes:
  redis-data:
  minio:
  db-data:
