version: '3.5'
services:
  db:
    environment:
      POSTGRES_PASSWORD: psuauthproxy
      POSTGRES_USER: psuauthproxy
      POSTGRES_DB: psuauthproxy
    image: postgres:10
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "5433:5432"
  web:
    tty: true
    stdin_open: true
    environment: 
      OIDC_SIGNING_KEY: ${OIDC_SIGNING_KEY:-"Zm9vCg=="}
      OIDC_ISSUER: ${OIDC_ISSUER:-http://localhost:3000}
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
      POSTGRES_USER: psuauthproxy
      POSTGRES_HOST: db
      POSTGRES_DB: psuauthproxy
      POSTGRES_PASSWORD: psuauthproxy
    build: 
      context: .
      target: base
    volumes:
      - /app/vendor/bundle
      - /app/node_modules
      - type: bind
        source: .
        target: /app/
        consistency: cached
    ports:
    - "3001:3000"
    depends_on:
    - db

volumes:
  db-data:
